@Ordering.Clinet_HostAddress = http://localhost:5078

GET {{Ordering.Clinet_HostAddress}}/weatherforecast/
Accept: application/json

###


/*
Test Data
{
  "orderId": 1,
  "userID": 2,
  "items": [
    {
      "id": 1,
      "quantity": 2,
      "price": 10
    },
    {
      "id": 3,
      "quantity": 3,
      "price": 20
    }
  ]
}    
*/